# Generated by Django 4.1.1 on 2022-11-12 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0003_billing_report_local_first_name_local_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='name_account',
        ),
        migrations.RemoveField(
            model_name='local',
            name='user',
        ),
        migrations.AddField(
            model_name='local',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='local',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='number_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.local'),
        ),
    ]
