# Generated by Django 4.1.1 on 2022-11-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_remove_local_name_account_remove_local_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='pdf/', verbose_name='Sprawozdanie PDF'),
        ),
    ]
