# Generated by Django 4.1.1 on 2022-11-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_alter_report_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='file',
            new_name='file_report',
        ),
    ]
