# Generated by Django 4.1.1 on 2022-11-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_rename_file_report_file_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file_report',
        ),
    ]
