# Generated by Django 4.1.1 on 2022-11-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_alter_billing_id_alter_report_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='local',
            name='last_name',
        ),
    ]
