# Generated by Django 4.1.1 on 2022-11-26 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0009_remove_local_first_name_remove_local_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'local', 'verbose_name_plural': 'local'},
        ),
        migrations.AddField(
            model_name='billing',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Termin płatności'),
        ),
    ]
