# Generated by Django 4.1.1 on 2022-12-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_alter_local_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id_b',
        ),
        migrations.RemoveField(
            model_name='report',
            name='number_local',
        ),
        migrations.AddField(
            model_name='report',
            name='file_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nazwa pliku'),
        ),
        migrations.AddField(
            model_name='report',
            name='my_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
