# Generated by Django 4.1.1 on 2022-12-15 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0013_billing_addressee_name_billing_bank_account_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comemnt',
            new_name='Comment',
        ),
        migrations.AlterField(
            model_name='billing',
            name='addressee_name',
            field=models.TextField(blank=True, null=True, verbose_name='Adresat rachunku'),
        ),
    ]
